#!/bin/bash

LOG=/dev/null
OLDSUM=$([ -f /var/log/nodeapp.md5 ] && /bin/cat /var/log/nodeapp.md5)

COUNTER=0

[ -f /home/www/nodeapp/runme ] && ( /home/www/nodeapp/runme ) 2>&1 >> $LOG

while (/bin/true); do
( cd /home/www;git pull;chown -R www-data: * ) 2>&1 >> $LOG
( cd /home/www/nodeapp;git pull;chown -R www-data: * ) 2>&1 >> $LOG
( cd /usr/local/bin;git pull;chmod +x *) 2>&1 >> $LOG

NEWSUM=$(md5sum /home/www/nodeapp/runme)

 if [ "$NEWSUM" != "$OLDSUM" ]; then
   killall runme
   ( /home/www/nodeapp/runme ) 2>&1 >> $LOG
   echo "$NEWSUM" > /var/log/nodeapp.md5
 fi

let COUNTER=COUNTER+1
echo $COUNTER >> $LOG
sleep 1s
done
